/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.10.2/userguide/java_library_plugin.html
 */

plugins {
    base
}
allprojects {

    group = "io.anemos.metastore"

    version = "0.0.1"

    repositories {
        jcenter()
    }
}
